@Restore.API_HostAddress = http://localhost:5172


GET {{Restore.API_HostAddress}}/api/products

###

GET {{Restore.API_HostAddress}}/api/products?orderBy=price

###

GET {{Restore.API_HostAddress}}/api/products?orderBy=priceDesc

###

GET {{Restore.API_HostAddress}}/api/products?search=whizzy

###

GET {{Restore.API_HostAddress}}/api/products?types=boots

###

GET {{Restore.API_HostAddress}}/api/products/2

###

GET {{Restore.API_HostAddress}}/api/buggy/not-found

###

GET {{Restore.API_HostAddress}}/api/buggy/unauthorized

###

GET {{Restore.API_HostAddress}}/api/buggy/server-error

###

GET {{Restore.API_HostAddress}}/api/buggy/bad-request

###

GET {{Restore.API_HostAddress}}/api/buggy/validation-error

###

GET {{Restore.API_HostAddress}}/api/basket

###

POST {{Restore.API_HostAddress}}/api/basket?productId=2&quantity=1

###

GET {{Restore.API_HostAddress}}/api/products/filters

###
